# Telegram client configuration
telegram:
  api_id: <your API ID from https://my.telegram.org>
  api_hash: <your API hash from https://my.telegram.org>
  session_file: /path/to/your/client.session

  # Chat types which should be monitored
  chat_types:
    - contact # Users added as contact
    - user # Users not added as contact
    - group # Groups (including mega groups)
    - channel # Channels (excluding mega groups)

  # List of chats to monitor additionally to those specified using "chat_types"
  # The command "list-chats" can be used to get specific IDs
  additional_chats:
    - <id 1>
    - <id 2>
    - ...

# Elasticsearch client configuration
elasticsearch:
  host: http://your-elastic-host:9200

  # Username and password used to authenticate at Elasticsearch (optional)
  username: <Elasticsearch user>
  password: <Elasticsearch password>

  index:
    # Specify the date format to use as the index suffix
    # "-" is automatically added between the prefix and the date
    # The following configuration will result in an index like "telegram-2020.03.18"
    # Without "date_format" the index will be named "telegram"
    date_format: "%Y.%m.%d"
    prefix: telegram