# Telegram client configuration
telegram:
  api_id: <your API ID from https://my.telegram.org>
  api_hash: <your API hash from https://my.telegram.org>
  session_file: /path/to/your/client.session

  # Chat types which should be monitored
  chat_types:
    - contact # Users added as contact
    - user # Users not added as contact
    - group # Groups (including mega groups)
    - channel # Channels (excluding mega groups)

  # List of chats to monitor additionally to those specified using "chat_types"
  # The command "list-chats" can be used to get specific IDs
  additional_chats:
    - <id 1>
    - <id 2>
    - ...

outputs:
    # Send messages to Elasticsearch
  - type: elastic
    host: http://your-elastic-host:9200

    # Username and password used to authenticate at Elasticsearch (optional)
    username: <Elasticsearch user>
    password: <Elasticsearch password>

    # Format of the index to use (will be passed to strftime)
    index_format: "telegram-%Y.%m.%d"

    # Send messages to any host using TCP (e.g. for using TCP input of Logstash)
  - type: tcp
    host: some-host
    port: 1234

    # Write messages to a file (in JSON format - one JSON object per line)
  - type: file
    path: /path/to/your/file.log