name: Build release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: programie/Workflows/.github/workflows/package-zip-release.yml@main
    with:
      files: telegram2elastic.py output config.sample.yml requirements.txt
      artifact_name: Telegram2Elastic.zip