name: Rebuild latest release

on:
  schedule:
    - cron: '0 0 * * SUN'

jobs:
  build:
    uses: programie/Workflows/.github/workflows/build-docker-image.yml@main
    with:
      image: programie/telegram2elastic
      use_latest_release: true
    secrets: inherit